Replaced URL environment variables for newman in ci-cd.yml ; make tes…
JesseMattson/PurrgentCare pull request #72
Opened 2024-08-12 14:44 UTC by JesseMattson

…t-backend-pipeline is failing

2024-08-12 16:45 UTC, RandallKeur commented
1. Could we also add some documentation around how to add github secrets for future reference so when we need to add more URLs or secrets, we have the documentation readily available? (highly encouraged)
2. Maybe given the errors we were seeing locally, maybe some documentation around Github actions may help too? (Non-blocking)

2024-08-20 01:09 UTC, RandallKeur requested changes
I can't highlight it for some reason but downgrade to node version 20.
See tested pipeline [here](https://github.com/JesseMattson/PurrgentCare/actions/runs/10463429520)

2024-08-20 01:10 UTC, RandallKeur commented on makefile
> +#TODO use docker to run application so we can run postman without needing two terminals
Love this idea, sounds like another feature we can work on next 😄

2024-08-20 17:18 UTC, JesseMattson commented on .github/workflows/ci-cd.yml
> +          node-version: '20'
@RandallKeur let me know if there was anywhere else this needed to be changed.

2024-08-21 00:13 UTC, RandallKeur approved these changes

2024-08-21 11:59 UTC, merged